<h2> Checking grid increments / size and first for 0.5 deg grid file for cfsv2 comparions </h2>

In [2]:
#imports
import pandas as pd

In [20]:
#training set
h5df = pd.read_hdf('./results-xgboost-tmp2m-highres.h5', 'test')
h5df.reset_index(inplace=True)
h5df

,start_date,lat,lon,xgboost_tmp2m_pred_zscore,tmp2m_daily_mean,tmp2m_daily_std,tmp2m_zscore,tmp2m,xgboost_tmp2m_pred
0,2019-10-01,27.25,260.75,0.707924,23.599968,2.310135,0.051498,23.718935,25.235367
1,2019-10-01,27.25,261.25,0.748031,22.827616,2.157367,0.014008,22.857836,24.441393
2,2019-10-01,27.25,261.75,1.026161,22.870967,2.045002,-0.014837,22.840626,24.969468
3,2019-10-01,27.25,262.25,0.861417,23.254119,2.007847,-0.030041,23.193802,24.983714
4,2019-10-01,27.25,277.75,0.605261,23.886820,1.095936,3.186881,27.379438,24.550148
...,...,...,...,...,...,...,...,...,...
310695,2020-07-28,47.75,270.25,0.716184,17.237201,1.527040,0.964266,18.709673,18.330842
310696,2020-07-28,47.75,270.75,0.483909,17.409569,1.449542,1.242080,19.210016,18.111015
310697,2020-07-28,47.75,271.25,0.616356,17.483455,1.408094,1.405506,19.462540,18.351342
310698,2020-07-28,47.75,271.75,0.372980,17.424084,1.362371,1.454398,19.405514,17.932221
310699,2020-07-28,47.75,272.25,0.314570,16.998357,1.360374,1.344960,18.828005,17.426290

In [4]:
h5df['key'] = h5df['start_date'].astype(str) + "|" + h5df['lat'].astype(str) + "|" + h5df['lon'].astype(str)
h5df

,start_date,lat,lon,xgboost_tmp2m_pred_zscore,tmp2m_daily_mean,tmp2m_daily_std,tmp2m_zscore,tmp2m,xgboost_tmp2m_pred,key
0,2013-12-04,27.25,260.75,-0.444575,14.477173,2.051871,-0.306895,13.847465,13.564963,2013-12-04|27.25|260.75
1,2013-12-04,27.25,261.25,-0.399303,14.199499,1.951358,-0.225235,13.759985,13.420315,2013-12-04|27.25|261.25
2,2013-12-04,27.25,261.75,-0.429326,14.463642,1.931331,-0.141234,14.190873,13.634471,2013-12-04|27.25|261.75
3,2013-12-04,27.25,262.25,-0.425091,14.828850,1.963461,-0.109792,14.613278,13.994200,2013-12-04|27.25|262.25
4,2013-12-04,27.25,277.75,0.390466,17.885119,2.932417,0.858304,20.402023,19.030128,2013-12-04|27.25|277.75
...,...,...,...,...,...,...,...,...,...,...
7764388,2020-10-06,47.75,270.25,-2.606435,4.096629,2.030455,-2.627814,-1.239028,-1.195618,2020-10-06|47.75|270.25
7764389,2020-10-06,47.75,270.75,-2.271173,4.436356,1.982421,-2.204216,0.066671,-0.066067,2020-10-06|47.75|270.75
7764390,2020-10-06,47.75,271.25,-2.178175,4.620783,1.995103,-2.001210,0.628163,0.275098,2020-10-06|47.75|271.25
7764391,2020-10-06,47.75,271.75,-2.075516,4.778328,1.958868,-2.032807,0.796327,0.712666,2020-10-06|47.75|271.75
7764392,2020-10-06,47.75,272.25,-2.178154,4.835887,1.877045,-2.160307,0.780893,0.747393,2020-10-06|47.75|272.25

In [ ]:
print(str(h5df.start_date.min()) + "|" + str(h5df.start_date.max()))

In [22]:
print(str(h5df.start_date.min()) + "|" + str(h5df.start_date.max()))
print(str(h5df['lat'].min()) + "|" + str(h5df['lat'].max()))
print(str(h5df['lon'].min()) + "|" + str(h5df['lon'].max()))

2019-01-01 00:00:00|2020-11-24 00:00:00
27.25|47.75
237.75|292.25

In [5]:
df = pd.read_csv("results_train.csv", encoding="utf-8")
df

,Unnamed: 0,Unnamed: 0.1,key,start_date,lat,lon,xgboost_tmp2m_pred_zscore,tmp2m_daily_mean,tmp2m_daily_std,tmp2m_zscore,tmp2m,xgboost_tmp2m_pred,err,phys,phys_err
0,0,0,2021-06-06|27.25|261.75,2021-06-06,27.25,261.75,-0.365524,29.645612,0.822407,-0.367244,29.343588,29.345002,0.001414,27.940800,-1.402788
1,1,1,2021-06-06|27.25|277.75,2021-06-06,27.25,277.75,0.174511,27.831134,0.771009,0.109562,27.915607,27.965684,0.050076,27.020874,-0.894733
2,2,2,2021-06-06|27.25|279.75,2021-06-06,27.25,279.75,0.028807,27.590214,0.836094,0.016340,27.603876,27.614299,0.010423,27.000971,-0.602905
3,3,3,2021-06-06|29.25|259.75,2021-06-06,29.25,259.75,-0.093218,30.306964,1.544366,0.026812,30.348372,30.163001,0.185370,27.398865,-2.949507
4,4,4,2021-06-06|29.25|261.75,2021-06-06,29.25,261.75,-0.194776,29.067243,1.383833,-0.136240,28.878710,28.797706,0.081003,25.834566,-3.044144
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536623,141047,1965,2013-12-23|47.25|265.75,2013-12-23,47.25,265.75,-0.489474,-12.713110,3.918168,0.015019,-12.654262,-14.630952,1.976691,-16.324123,-3.669862
536624,141048,1966,2013-12-23|47.25|267.75,2013-12-23,47.25,267.75,-0.600570,-12.486296,3.774824,-0.261513,-13.473462,-14.753342,1.279880,-15.931176,-2.457714
536625,141049,1967,2013-12-23|47.25|269.75,2013-12-23,47.25,269.75,-0.524695,-10.677083,3.378909,-0.109543,-11.047218,-12.449980,1.402762,-12.161458,-1.114240
536626,141050,1968,2013-12-23|47.25|271.75,2013-12-23,47.25,271.75,-0.776035,-8.561244,3.038736,-0.419888,-9.837173,-10.919409,1.082236,-8.457057,1.380116
536627,141051,1969,2013-12-23|47.25|273.75,2013-12-23,47.25,273.75,-0.867268,-6.805904,3.622605,-0.768027,-9.588163,-9.947675,0.359511,-6.299348,3.288815

In [15]:
print(str(df['lat'].min()) + "|" + str(df['lat'].max()))
print(str(df['lon'].min()) + "|" + str(df['lon'].max()))

27.25|47.25
237.75|291.75

In [19]:
print((291.75 - 237.75)/2)

27.0